list: $/mavitm/staff/models/staff/columns.yaml
modelClass: Mavitm\Staff\Models\Staff
title: StafAre
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mavitm/staff/staffare/update/:id'
filter: config_filter.yaml
